mozilla/all-aboard

data/js/utility/content3.js
index.js

This PR adds the switch case for the theme button clicks, as well as the function needed to change the user's theme.
Issue ref: #16

Issue 16 - Utility 3 - Add theme clicking-preview functionality

---

data/js/utility/content4.js
index.js

This PR adds the switch case for the 'try it now' button on the awesome-bar utility sidebar 4.
Issue ref: #17

Issue 17 - Utility 4 - Add awesomebar highlighting

---

data/js/utility/content4.js

Emits are case sensitive and I forgot to change the case of the emit from front-end js.
Issue ref: #34

Fix captialization - Issue 17 - Utility sidebar 4

---

data/js/values/content3.js
data/tmpl/values/content3.html
index.js

Fix issue#22, values privacy sidebar

---

.eslintrc.js
.gitignore
.jpmignore
README.md
index.js

WIP, will ping @FrancescoSTL as soon as it is ready for review.

Make add-on configurable

---

data/css/about-home.css
data/js/about-home.js
data/tmpl/values/content1-snippet.html
index.js

Issue#28 snippet override base

---

data/js/about-home.js
data/tmpl/utility/content1-snippet.html
data/tmpl/values/content1-snippet.html

Merging without review for now.

Adds values snippet for content 1 and moves utility snippet

---

index.js

Fix issue #69, sidebarProps undefined on subsequent sidebar toggle

---

index.js

Fix issue #70, call showBadge and not toggleSidebar on browser startup

---

index.js

Fix issue #78, fix showing and closing of sidebars before and after notifications

---

data/css/all-aboard.css
data/js/show_data.js
data/tmpl/show_data.html
index.js

This is a big one. The first iteration of our auto-import preview for users to see some of the bookmark/history data they've imported. For now, the "reset import" button is non-functional, as we will need the platform team to build that out before we are able to make it work.
r? @schalkneethling

Issue 38 user data import sidebar

---

data/js/utility/content1.js
data/js/utility/content2.js
data/js/utility/content3.js
data/js/utility/content4.js
data/js/values/values.js
index.js

Fix issue #79, award tokens on completion of main CTA

---

data/css/all-aboard.css

@FrancescoSTL r? This gives an even spacing of 40px above and below the multiple question section

Fix issue #99, reduce margin below header on values track

---

data/css/all-aboard.css

Fix issue #102, reduce spacing on values headers by 50%

---

data/css/all-aboard.css

Reducing space between bottom of sidebar-content and top of tokens to 40px.
Issue ref: #94

Issue 94 - Reduce margin above tokens to 40px

---

data/js/values/values.js

Fix issue #103, remove tell me if secondary content

---

data/js/utility/content5.js

Fix issue #104, add js for utility content 5

---

index.js

Fix issue #86, start timer on token assign

---

index.js

Dismissing the awesomebar when it comes into focus.
Issue ref: #97

Issue #97 - Dismiss Awesomebar Highlight Onclick

---

index.js

It is currently 12:05 AM and I'm pretty tired but I'm fairly certain this is the best way to solve the issue 🇺🇸 💻 
Issue ref: #113 
r? @schalkneethling

Fix Issue 113- Multiple Notifications w/ CTA Click

---

data/tmpl/values/content1.html
data/tmpl/values/content2.html
data/tmpl/values/content3.html
data/tmpl/values/content4.html
data/tmpl/values/content5.html

Fix issue #122 - Tell me to show me

---

data/tmpl/utility/content4.html

Issue ref #119 @schalkneethling r?

Issue #119 - Set Utility 4 Copy 🇬🇧

---

.jpmignore

Add latest XPI and add .git to jpmignore to reduce filesize

---

data/tmpl/values/content1.html
data/tmpl/values/content2.html
data/tmpl/values/content3.html
data/tmpl/values/content4.html
data/tmpl/values/content5.html

Change "show me" to "show answer"

---

data/js/values/values.js

r? @schalkneethling or @chrismore

Issue #101 - Disable wrong answer buttons

---

data/js/firstrun.js

The `<br>`'s are a temp fix for our demo in 5 min. We can add margin later.

Fix firstrun text and temp add <br> for yup/nope

---

data/tmpl/utility/content4.html

Removed word "here" as per convo w/ Chris, Justin, Fabio for demo

Change to remove "here" in utility 4 copy

---

data/tmpl/import_data.html

Issue ref: #134 
r? @chrismore

Issue #134 - Change import data header

---

data/tmpl/values/content1-snippet.html
data/tmpl/values/content2-snippet.html
data/tmpl/values/content4-snippet.html
data/tmpl/values/content4.html
data/tmpl/values/content5-snippet.html
data/tmpl/values/content5.html

Fix issue #147, add utm params to external links

---

data/css/firstrun.css
data/js/firstrun.js

Fix issue #148, move no thanks to below first container

---

data/tmpl/values/content3.html

Issue ref: #142 
r? @chrismore

Issue #142 - Values Privacy Sidebar Copy

---

data/tmpl/utility/content5.html

Issue ref: #139 
r? @chrismore

Issue #139 - Mobile Utility Sidebar Copy

---

index.js
lib/utils.js
test/test-index.js

Adds initially set of unit tests

---

data/tmpl/utility/content5.html

Issue #98 - Add adjust links to mobile buttons

---

data/tmpl/utility/content5.html

Fix issue #140, ensure app and play store badges are the same width

---

data/css/firstrun.css
data/js/firstrun.js

Fix issue #144, toggle no thanks copy between questions interaction and fxa form

---

data/css/all-aboard.css
data/js/values/values.js
data/tmpl/values/content1.html
data/tmpl/values/content2.html
data/tmpl/values/content3.html
data/tmpl/values/content4.html
data/tmpl/values/content5.html

Fix issue #143, hide button and show success message, values sidebars

---

index.js

@chrismore r? I believe this also fixes https://github.com/mozilla/all-aboard/issues/132

Fix issue #85, toggle existing sidebar when icon clicked

---

index.js

Fix issue #135, updated copy for desktop notifications

---

README.md
index.js

@chrismore r?
Note the additions to `config.json` below for the new timers:
```
{
....
"afterInteractionCloseTime": 2000,
"defaultSidebarCloseTime": 5000,
....
}
```

Fix issue #137, auto close sidebar timers

---

data/css/firstrun.css
data/js/firstrun.js

Fix issue #175, fix modify script for new firstrun

---

data/css/firstrun.css
data/js/firstrun.js
data/tmpl/firstrun.html
index.js

@chrismore r?
Here is how the layout looks. With some of the layout changes, I was not exactly sure where we wanted the copy added, so I took a stab at it.

Fix issue #133, add intro copy to firstrun questions

---

.gitignore
.jpmignore
circle.yml
package.json

@FrancescoSTL I will probably need to merge this in order to test that everything works as expected. If there is anything you notice that seems to require a second look, let me know. Thanks!

Fix issue #52, auto build xpi and run tests

---

data/tmpl/firstrun.html
index.js

Now we are randomizing the utility vs values options.
Issue ref: #125 
r? @schalkneethling

Issue #125 - Randomize Firstrun Question Answers

---

data/tmpl/firstrun.html
data/tmpl/fragments/what-matters-option1.html
data/tmpl/fragments/what-matters-option2.html
index.js

Fix issue #197, use html fragments to ensure label and input elements are associated

---

data/css/all-aboard.css
data/tmpl/reward.html

Fix issue #178, adds reward form iframe from heroku

---

data/js/firstrun.js

Fix issue #33, updates iframe src attribute

---

data/tmpl/firstrun.html

Issue #133 - Update Intro Copy

---

index.js

Adds active state for icon actionButton
issue ref: #66 
r? @schalkneethling

Issue #66 - Add icon active state

---

data/css/all-aboard.css
data/js/utility/content3.js
data/tmpl/utility/content3.html
data/tmpl/values/content3.html
data/tmpl/values/content4.html
data/tmpl/values/content5.html

Still need to sort out the private browsing text on values sidebar 3, and update utility sidebar 3 (themes).

Issue #127 - Make sidebar "responsive"

---

index.js

Issue #214 - Reduce theme ID array

---

index.js

Issue #213 - Fix Smarton/newsletter URL

---

index.js

Fix issue #181, do not show questions if they have already been answered

---

data/css/about-newtab.css
data/js/about-newtab.js
data/tmpl/about-newtab-footer.html
data/tmpl/about-newtab-header.html
index.js

Updated experience: 
Issue ref: #211

Issue #211 - Add Newtab Feature Highlight/ Change copy

---

data/tmpl/utility/content3.html

Issue ref: #191 
The issue is referring to more than just editing the link, but we solved all of that in #205 
@chrismore r?

Issue #191 - Edit Explore Themes Link

---

README.md
data/css/all-aboard.css
data/js/lib/token-manager.js
data/js/values/values.js
data/tmpl/utility/content1-snippet.html
data/tmpl/utility/content1.html
data/tmpl/utility/content2.html
data/tmpl/utility/content3.html
data/tmpl/utility/content4.html
data/tmpl/utility/content5.html
data/tmpl/values/content1.html
data/tmpl/values/content2.html
data/tmpl/values/content3.html
data/tmpl/values/content4.html
data/tmpl/values/content5.html
index.js

@FrancescoSTL r? The covers:
* https://github.com/mozilla/all-aboard/issues/64
* https://github.com/mozilla/all-aboard/issues/179

Fix issue #64, make badges clickable

---

index.js

Missing ending ); throwing syntax error. This fixes that.

Fix syntax error with ending );

---

index.js

Fix issue #221, add action button to chrome on startup if user has seen step 1

---

data/css/all-aboard.css
data/js/reward.js
data/js/utility/content5.js
data/js/values/values.js
data/tmpl/reward.html
data/tmpl/utility/content5.html
data/tmpl/values/content5.html
index.js

Issue ref: #158 
@schalkneethling r?

Issue #158 - Add "Claim your prize" link 🐺`

---

data/css/all-aboard.css

@chrismore @FrancescoSTL just an FYI: To enable me to move forward, and avoid a potential merge nightmare. I am going to merge as I go for today. Any work that I only get to tomorrow (5 July) I will leave pull requests open for.

Fix issue #232, define iframe height at 220px

---

data/tmpl/values/content3.html

@FrancescoSTL r? This problem is actually on content 3 of the values track

Fix issue #228, correct messpelling on content 4 value track

---

index.js

Fix issue #229, change copy on lightbuld hover

---

index.js

Fix issue #233, delay notifications on startup by 60 seconds

---

.jpmignore
data/js/about-newtab.js
index.js

We need to comment out the logic for undoing auto-import 
Issue ref: #249

Issue #249 - Add Undo Import

---

data/js/about-home.js
data/tmpl/utility/content1-snippet.html
data/tmpl/utility/content2-snippet.html
data/tmpl/utility/content3-snippet.html
data/tmpl/utility/content4-snippet.html
data/tmpl/utility/content5-snippet.html
data/tmpl/values/content1-snippet.html
data/tmpl/values/content2-snippet.html
data/tmpl/values/content3-snippet.html
data/tmpl/values/content4-snippet.html
data/tmpl/values/content5-snippet.html
index.js

This is only rotation non-reward snippets for now, and also fixes the issue caused in #245 where snippet content isn't loaded.
Issue ref: #67

Issue #67 - Snippet Rotation + Fix null snippet bug

---

data/css/all-aboard.css
data/js/lib/token-manager.js
data/js/utility/content5.js
data/js/values/values.js
data/tmpl/utility/content1.html
data/tmpl/utility/content2.html
data/tmpl/utility/content3.html
data/tmpl/utility/content4.html
data/tmpl/utility/content5.html
data/tmpl/values/content1.html
data/tmpl/values/content2.html
data/tmpl/values/content3.html
data/tmpl/values/content4.html
data/tmpl/values/content5.html
index.js

Fix issue #166, adds heres you badge to all tracks

---

index.js

Fix issue #225, do not close first sidebar if visible before first notification

---

index.js
lib/utils.js
test/test-index.js

Fix issue #123, check distribution.id before updating

---

data/css/about-newtab.css
data/js/about-newtab.js
data/tmpl/about-newtab-header.html
index.js

Cleaning up some things as noted in #253

Issue #253 - Newtab Not Modified

---

data/tmpl/about-newtab-footer.html

Fixes newtab footer left align
Issue ref: #262

Issue #262 - Center align newtab footer

---

index.js

Fix issue #40, hide sidebar title text

---

index.js

Fixes issue #277.
@chrismore r?

Issue #277 - Open Newtab on Navigation Away from FXA

---

data/js/utility/content3.js
data/js/utility/content5.js
data/tmpl/utility/content3.html
data/tmpl/utility/content5.html
index.js

This resolves #276 
@chrismore are we wanting to open up all links in a new tab as @schalkneethling mentioned in the bug? Currently the other links which will open up in a new window:
1. Mobile app badges on utility content 5
2. Various snippet links

Issue #276 - Open Links in New Window

---

index.js

Issue #273 - Close Prize Sidebar on Badge Click

---

README.md
data/css/all-aboard.css
package.json

Everything looks good. Thanks @chrismore!

Issue#283 no scroll changes

---

index.js

This should reflect the working code @chrismore had in his previous PR, but with a rebase.
Note: This won't implement copy rotation for the reward snippet. If that is something we'd like to do, it is not tough. Not a top priority right now, in my mind. Thoughts? @chrismore

Issue #291 - Add Reward Snippet

---

index.js

Issue #294 - Dismiss Highlight Bookmark

---

index.js

**This PR should fix multiple problems:**
1. The last PR left an issue with the actionButton never showing up after the first session if the user didn't click the CTA because of a condition in the else of the first conditional in exports.main. This is fixed.
2. We added a fix to catch users who are currently in the anomaly of having no `lastSidebarLaunchTime` (now `lastSidebarCTACompleteTime`) who will get this update when we sign. Now they should have a 60 second notification starting upon time of launch. Setting the `lastSidebarCTACompleteTime` to 24 hours prior to run time will also fix the issue in the future between sessions.
3. In the last PR, we would start a 60 second notification everytime a session was started past the 24 hour period for the notification, even if the user had …

Issue #303 - Notification Not Showing

---

README.md

@FrancescoSTL It works \o/ - This just adds a build status badge to the README

Adds TravisCI status badge showing current status of build

---

.gitignore
.jpmignore
README.md
data/js/firstrun.js
index.js
tests-functional/.gitignore
tests-functional/.travis.yml
tests-functional/LICENSE
tests-functional/pages/__init__.py
tests-functional/pages/about_home.py
tests-functional/pages/all_aboard.py
tests-functional/pages/firstrun.py
tests-functional/setup.cfg
tests-functional/tests/__init__.py
tests-functional/tests/conftest.py
tests-functional/tests/test_all_aboard_values.py
tests-functional/tests/test_firstrun.py
tests-functional/tox.ini

@FrancescoSTL I still need to add a bunch of documentation on using the framework and writing tests so, I am leaving this as WIP for now. It works though so \o/

Adds marionette and selenium for functional tests

---

tests-functional/tests/conftest.py

@FrancescoSTL alrighty, so now all the tests run successfully.

Adds back accidentally removed marionette capability

---

tests-functional/pages/sidebar.py
tests-functional/tests/test_all_aboard_values.py

Adds functional test for flow from firstrun to second sidebar notification

---

tests-functional/pages/sidebar.py
tests-functional/tests/test_all_aboard_values.py

@FrancescoSTL expansion on tests for values track

Additional tests for values flow

---

data/js/about-home.js
data/tmpl/reward-snippet.html
data/tmpl/utility/content1-snippet.html
data/tmpl/utility/content2-snippet.html
data/tmpl/utility/content3-snippet.html
data/tmpl/utility/content4-snippet.html
data/tmpl/utility/content5-snippet.html
data/tmpl/values/content1-snippet.html
data/tmpl/values/content2-snippet.html
data/tmpl/values/content3-snippet.html
data/tmpl/values/content4-snippet.html
data/tmpl/values/content5-snippet.html
index.js
lib/content-scripts/about-home.js
lib/content-scripts/firstrun.js
lib/content-scripts/snippets.js
lib/notification-manager.js
lib/scheduler.js
lib/sidebar-events.js
lib/sidebar-manager.js
lib/tokens-manager.js
lib/utils.js

Fix issue #335, TG-176 #closed, change snippet cta to open sidebar

---

lib/sidebar-manager.js
lib/utils.js

Fix issue #346, resolve self paced progression bug

---

data/js/values/values.js
lib/sidebar-manager.js
lib/utils.js
test/test-utils.js

Simplify load next as calculations are not needed

---

lib/notification-manager.js

Only auto open first sidebar on first notification

---

data/tmpl/reward-snippet.html
lib/content-scripts/about-home.js
lib/content-scripts/snippets.js

Updates to snippets copy and logic

---

.travis.yml
data/js/lib/common.js
data/js/utility/content1.js
data/js/utility/content2.js
data/js/utility/content3.js
data/js/utility/content4.js
data/js/values/values.js
package.json

@schalkneethling - I think this would help with doing code level reviews. I haven't tested this but hopefully we can get this working fairly easily.

Run ESLint in Travis CI

---

data/tmpl/firstrun.html
data/tmpl/fragments/what-matters-option1.html
data/tmpl/fragments/what-matters-option2.html

Fix issue #355, update onboarding questions

---

.jpmignore
data/tmpl/reward.html
tests-functional/pages/all_aboard.py
tests-functional/pages/sidebar.py
tests-functional/tests/conftest.py
tests-functional/tests/test_all_aboard_sidebar.py
tests-functional/tests/test_all_aboard_values.py
tests-functional/tests/test_positive_values_user_flow.py

@alexgibson @davehunt r? I am specifically looking for how to make the code more succinct, more pythonic and generally follow best practices when it comes to writing these tests. Thanks in advance.

Adds functional tests for successful values flow
